name: John Domzalski
favicon: null
layout_spectrum: 0.62034
typography_spectrum: 0.36367
title: John Domzalski Home Business Success tips
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#272727'
    - '#ebeae6'
    - '#516a90'
    - '#0c590e'
    - '#9f9e99'
  brandStrength: 0
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 0
purpose: []
