name: John Domzalski
favicon: null
layout_spectrum: 0.62034
typography_spectrum: 0.36367
title: John Domzalski Home Business Success tips
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
